services:
  - type: web
    name: dinelytics
    env: php
    buildCommand: |
      composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
      php artisan key:generate --force
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      npm install
      npm run build
      php artisan migrate:fresh --seed --force
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    envVars:
      - key: APP_URL
        fromService:
          type: web
          name: dinelytics
          property: url
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
    disk:
      - name: sqlite-data
        mountPath: /var/www/html/database
        sizeGB: 1

